<a href='https://pandas.pydata.org/docs/'> 🌐 Pandas Docs</a>
<img src="../supporting_items/Pandas_logo.svg.png" width="200" height="100" />

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [6]:
import pandas as pd
import numpy as np

In [7]:
from numpy.random import randn
np.random.seed(101)

In [8]:
#Show multiple ways to create a DataFrame
import pandas as pd
#From Dictionaries of List
data = {
    "Name": ["Amit", "Rahul", "Sneha"],
    "Age": [25, 28, 22],
    "City": ["Hyderabad", "Delhi", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age       City
0   Amit   25  Hyderabad
1  Rahul   28      Delhi
2  Sneha   22     Mumbai

In [9]:
#From List of Dictionaries
data = [
    {"Name": "Amit", "Age": 25, "City": "Hyderabad"},
    {"Name": "Rahul", "Age": 28, "City": "Delhi"},
    {"Name": "Sneha", "Age": 22, "City": "Mumbai"}
]

df = pd.DataFrame(data)
print(df)

    Name  Age       City
0   Amit   25  Hyderabad
1  Rahul   28      Delhi
2  Sneha   22     Mumbai

In [10]:
#From List of Lists
data = [
    ["Amit", 25, "Hyderabad"],
    ["Rahul", 28, "Delhi"],
    ["Sneha", 22, "Mumbai"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])
print(df)

    Name  Age       City
0   Amit   25  Hyderabad
1  Rahul   28      Delhi
2  Sneha   22     Mumbai

In [11]:
#From Numpy Array
import numpy as np
import pandas as pd

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [12]:
import pandas as pd
# From Series
s = pd.Series([10, 20, 30], name="Numbers")

df = pd.DataFrame(s)
print(df)

   Numbers
0       10
1       20
2       30

In [13]:
#please note that dataframes can be created directly from the contents of CSV, Excel, and any other structured file.

In [14]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
type(df)

pandas.core.frame.DataFrame

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [16]:
df['W'] # Searching for a particular column, the type is Series

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [17]:
df['W']['C']

np.float64(-2.018168244037392)

In [18]:
type(df['W'] )

pandas.core.series.Series

In [19]:
# Pass a list of column names
df[['W','X']]

          W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [20]:
type(df[['W','X']])

pandas.core.frame.DataFrame

In [21]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

In [22]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [23]:
df['new'] = df['W'] + df['Y']

In [24]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

** Removing Columns**

In [25]:
df.drop('new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [27]:
df.drop('new',axis=1,inplace=True)

In [28]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [30]:
df = df.drop('new', axis=1)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Can also drop rows this way:

In [31]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

** Selecting Rows**

In [32]:
#df.loc[row,col]
#df.loc[row_st: row_end, col_st:col_end]

In [33]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [34]:
type(df.loc['A'])

pandas.core.series.Series

Or select based off of position instead of label

In [35]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [36]:
df.loc['B','Y']

np.float64(-0.8480769834036315)

In [37]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [38]:
df.loc['A':'B', 'W':'Y']

          W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [39]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [41]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df[['W','X']]>0

       W      X
A   True   True
B   True  False
C  False   True
D   True  False
E   True   True

In [43]:
df[df[['W','X']]>0]

          W         X   Y   Z
A  2.706850  0.628133 NaN NaN
B  0.651118       NaN NaN NaN
C       NaN  0.740122 NaN NaN
D  0.188695       NaN NaN NaN
E  0.190794  1.978757 NaN NaN

In [44]:
type(df['W']>0)

pandas.core.series.Series

In [45]:
ser =pd.Series([True,True,False,False,False], index =['A','B','C','D','E'])
ser

A     True
B     True
C    False
D    False
E    False
dtype: bool

In [46]:

df[[True,True,False,False,False]]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [47]:
df[ser]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [48]:
print(df)
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df[df['W']>0][['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
D  0.188695 -0.933237
E  0.190794  2.605967

In [50]:
df[df['W']>0].loc[ :  , 'W':'Z':2]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
D  0.188695 -0.933237
E  0.190794  2.605967

For two conditions you can use | and & with parenthesis:

In [51]:
[(df['W']>0) & (df['Y'] > 1)]

[A    False
 B    False
 C    False
 D    False
 E     True
 dtype: bool]

In [52]:
df[(df['W']>0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [53]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [54]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [55]:
newind = 'CA NY WY OR CO'.split()

In [56]:
df['States'] = newind

In [57]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [58]:
df.set_index('States')

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [59]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [60]:
df.set_index('States',inplace=True)

In [61]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## 🗂️Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [62]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [63]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [64]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [65]:
df.loc['G1']

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [66]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [67]:
df.index.names

FrozenList([None, None])

In [68]:
df.index.names = ['Group','Num']

In [69]:
df

                  A         B
Group Num
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [70]:
df.xs('G1')

            A         B
Num
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [71]:
df.xs(['G1',1])

TypeError: list keys are not supported in xs, pass a tuple instead

In [ ]:
df.xs(1,level='Num')

              A         B
Group
G1    -0.993263  0.196800
G2    -0.031579  0.649826

# Great Job!

In [ ]:
df_mx = pd.DataFrame(np.random.randn(5,5),columns=['A','B','C','D','E'])
df_mx

          A         B         C         D         E
0 -0.568581  1.407338  0.641806 -0.905100 -0.391157
1  1.028293 -1.972605 -0.866885  0.720788 -1.223082
2  1.606780 -1.115710 -1.385379 -1.329660  0.041460
3 -0.411055 -0.771329  0.110477 -0.804652  0.253548
4  0.649148  0.358941 -1.080471  0.902398  0.161781

In [ ]:
df_mx = pd.DataFrame(np.random.randn(5,5),columns=['A','B','C','D','E'])
df_mx['index_columns'] = ['A','A','C','D','E']
df_mx = df_mx.set_index('index_columns')
df_mx

                      A         B         C         D         E
index_columns
A              0.833029  0.975720 -0.388239  0.783316 -0.708954
A              0.586847 -1.621348  0.677535  0.026105 -1.678284
C              0.333973 -0.532471  2.117727  0.197524  2.302987
D              0.729024 -0.863091  0.305632  0.243178  0.864165
E             -1.560931 -0.251897 -0.578120  0.236996  0.200780

## 📚 More to Read

### The Power of the Pandas Index

Think of a Pandas **Index** like the index at the back of a textbook or a primary key in a database. Without it, you’d have to scan every single page to find what you need.

### 1. Lightning-Fast Lookups
Instead of scanning every row (an $O(n)$ operation), Pandas uses the index to find data instantly. If you use `.loc['Label']`, Pandas uses a hash table to jump straight to that row.

### 2. Automatic Data Alignment
This is a "killer feature." When you perform math between two DataFrames, Pandas matches the **Index labels** rather than just adding row by row.
*   **Example:** If `df1` has index `[A, B]` and `df2` has `[B, C]`, adding them will automatically align the `B` values and leave `A` and `C` as `NaN`.

### 3. Easier Data Selection
Indexes allow you to use human-readable labels (like dates, names, or IDs) instead of remembering row numbers. Slicing becomes intuitive:
*   `df.loc['2023-01-01':'2023-01-31']` is much clearer than calculating the integer positions for a whole month.

### 4. Efficient Joining and Merging
When merging datasets, a common index makes the operation significantly faster and less memory-intensive. It acts as the "anchor" that keeps related data together.

### 5. Multi-Level Organization (MultiIndex)
You can have multiple indexes (Hierarchical Indexing). This allows you to work with higher-dimensional data (like **Year** > **Quarter** > **Month**) in a 2D table format while keeping it organized.

---

**Summary:** The index turns a simple array of numbers into a **searchable database** where data knows exactly where it belongs.

### 🧮 Categorical Data

- In a pandas DataFrame, categorical data is a specialized data type used for variables that take on a limited, fixed number of possible values—such as gender, blood type, or ratings. 

- Internally, pandas stores this as two separate components: a list of unique categories (strings or other types) and an integer array of codes that point to those categories. 

#### Key Benefits
- ***Memory Efficiency***: By storing small integers instead of repeating long strings, it can drastically reduce the memory footprint of large datasets. 

- ***Performance Boost***: Operations like sorting, grouping, and string manipulations (via .str accessor) are often much faster because they only need to be performed on the unique categories once. 

- ***Logical Ordering***: You can define a custom order (e.g., "Small" < "Medium" < "Large") that is respected during sorting and plotting, rather than just using alphabetical order. 

- ***Data Integrity***: It enforces a fixed set of values; assigning a value not in the defined categories will result in a NaN or error.

In [74]:
import pandas as pd

# Define data in a dictionary
data = {
    'Employee_ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'IT', 'Marketing'],
    'Salary': [50000, 75000, 82000, 60000]
}

# Create the DataFrame
df = pd.DataFrame(data)

print(df)

   Employee_ID     Name Department  Salary
0          101    Alice         HR   50000
1          102      Bob         IT   75000
2          103  Charlie         IT   82000
3          104    David  Marketing   60000

In [91]:
# 1. Convert existing column to categorical
df['Department'] = df['Department'].astype('category')

# 2. Define during creation with custom order
from pandas.api.types import CategoricalDtype
df_cat = pd.DataFrame(data)
department_type = CategoricalDtype(categories=['HR', 'Marketing', 'IT', 'HR2'], ordered=True)
df_cat['Department'] = df_cat['Department'].astype(department_type)

# 3. Access codes and categories
print(df['Department'].cat.codes)      # Returns integer mapping
print(df['Department'].cat.categories) # Returns ['HR', 'Marketing', 'IT']

0    0
1    2
2    2
3    1
dtype: int8
Index(['HR', 'Marketing', 'IT'], dtype='object')

In [94]:
# Update a value in the 'Department' column
# This will not work because 'HR2' is not in the defined categories
df_cat.loc[0, 'Department'] = 'HR2'  # This will work because 'HR2' is in the defined categories
df.loc[0, 'Department'] = 'HR2' # This will not work because 'HR2' is not in the defined categories

TypeError: Cannot setitem on a Categorical with a new category (HR2), set the categories first