# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from numpy.random import randn
np.random.seed(101)

In [1]:
#Show multiple ways to create a DataFrame
import pandas as pd
#From Dictionaries of List
data = {
    "Name": ["Amit", "Rahul", "Sneha"],
    "Age": [25, 28, 22],
    "City": ["Hyderabad", "Delhi", "Mumbai"]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
#From List of Dictionaries
data = [
    {"Name": "Amit", "Age": 25, "City": "Hyderabad"},
    {"Name": "Rahul", "Age": 28, "City": "Delhi"},
    {"Name": "Sneha", "Age": 22, "City": "Mumbai"}
]

df = pd.DataFrame(data)
print(df)

In [ ]:
#From List of Lists
data = [
    ["Amit", 25, "Hyderabad"],
    ["Rahul", 28, "Delhi"],
    ["Sneha", 22, "Mumbai"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])
print(df)

In [ ]:
#From Numpy Array
import numpy as np
import pandas as pd

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)

In [ ]:
import pandas as pd
# From Series
s = pd.Series([10, 20, 30], name="Numbers")

df = pd.DataFrame(s)
print(df)

In [ ]:
#please note that dataframes can be created directly from the contents of CSV, Excel, and any other structured file.

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [ ]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [ ]:
type(df)

pandas.core.frame.DataFrame

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [ ]:
df['W'] # Searching for a particular column, the type is Series

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [ ]:
df['W']['C']

np.float64(0.8077059142577141)

In [ ]:
type(df['W'] )

pandas.core.series.Series

In [ ]:
# Pass a list of column names
df[['W','X']]

          W         X
A  0.302665  1.693723
B -0.134841  0.390528
C  0.807706  0.072960
D -0.497104 -0.754070
E -0.116773  1.901755

In [ ]:
type(df[['W','X']])

pandas.core.frame.DataFrame

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

DataFrame Columns are just Series

In [ ]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

** Removing Columns**

In [ ]:
df.drop('new',axis=1)

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [ ]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [ ]:
df = df.drop('new', axis=1)
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

** Selecting Rows**

In [ ]:
#df.loc[row,col]
#df.loc[row_st: row_end, col_st:col_end]

In [ ]:
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [ ]:
type(df.loc['A'])

pandas.core.series.Series

Or select based off of position instead of label

In [ ]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [ ]:
df.loc['B','Y']

np.float64(0.16690463609281317)

In [ ]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [ ]:
df.loc['A':'B', 'W':'Y']

          W         X         Y
A  0.302665  1.693723 -1.706086
B -0.134841  0.390528  0.166905

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [ ]:
df>0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [ ]:
df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [ ]:
df[['W','X']]>0

       W      X
A   True   True
B  False   True
C   True   True
D  False  False
E  False   True

In [ ]:
df[df[['W','X']]>0]

          W         X   Y   Z
A  0.302665  1.693723 NaN NaN
B       NaN  0.390528 NaN NaN
C  0.807706  0.072960 NaN NaN
D       NaN       NaN NaN NaN
E       NaN  1.901755 NaN NaN

In [ ]:
type(df['W']>0)

pandas.core.series.Series

In [ ]:
ser =pd.Series([True,True,False,False,False], index =['A','B','C','D','E'])

In [ ]:
df[[True,True,False,False,False]]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502

In [ ]:
df[ser]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502

In [ ]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [ ]:
df[df['W']>0][['W','Y']]

          W         Y
A  0.302665 -1.706086
C  0.807706  0.638787

In [ ]:
df[df['W']>0].loc[ :  , 'W':'Z':2]

          W         Y
A  0.302665 -1.706086
C  0.807706  0.638787

For two conditions you can use | and & with parenthesis:

In [ ]:
[(df['W']>0) & (df['Y'] > 1)]

[A    False
 B    False
 C    False
 D    False
 E    False
 dtype: bool]

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
df['States'] = newind

In [ ]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df.set_index('States')

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [ ]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.153661  0.167638
   2 -0.765930  0.962299
   3  0.902826 -0.537909
G2 1 -1.549671  0.435253
   2  1.259904 -0.447898
   3  0.266207  0.412580

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df.loc['G1']

          A         B
1  0.153661  0.167638
2 -0.765930  0.962299
3  0.902826 -0.537909

In [ ]:
df.loc['G1'].loc[1]

A    0.153661
B    0.167638
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names = ['Group','Num']

In [ ]:
df

                  A         B
Group Num
G1    1    0.153661  0.167638
      2   -0.765930  0.962299
      3    0.902826 -0.537909
G2    1   -1.549671  0.435253
      2    1.259904 -0.447898
      3    0.266207  0.412580

In [ ]:
df.xs('G1')

            A         B
Num
1    0.153661  0.167638
2   -0.765930  0.962299
3    0.902826 -0.537909

In [ ]:
df.xs(['G1',1])

A    0.153661
B    0.167638
Name: (G1, 1), dtype: float64

In [ ]:
df.xs(1,level='Num')

              A         B
Group
G1     0.153661  0.167638
G2    -1.549671  0.435253

# Great Job!