<a href='https://pandas.pydata.org/docs/'> 🌐 Pandas Docs</a>
<img src="../supporting_items/Pandas_logo.svg.png" width="200" height="100" />

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [3]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [4]:
df.dropna() #inplace=True not done so its not getting effective in the original DF.
# axis=0 by default.

     A    B  C
0  1.0  5.0  1

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(axis=1) # Drop all the columns where you find any null value.

   C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2) # Atleast 1 non null value per row.

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df.fillna(value='FILL VALUE')

            A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [ ]:
df.fillna(df.mean()) # fill up all the columns with their mean value(mean value of the column). Only for numeric columns.

NameError: name 'df' is not defined

In [ ]:
# isna
#

# Great Job!

### Some more example