___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [1]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [2]:
df = pd.DataFrame(data)

In [3]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

** Now you can use the .groupby() method to group rows together based off of a column name. For instance let's group based off of Company. This will create a DataFrameGroupBy object:**

In [4]:
df.groupby('Company')

You can save this object as a new variable:

In [ ]:
by_comp = df.groupby("Company")

And then call aggregate methods off the object:

In [ ]:
by_comp.mean()

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [6]:
df.groupby('Company')['Sales'].sum()

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

More examples of aggregate methods:

In [7]:
df.groupby('Company')['Sales'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

In [8]:
df.groupby('Company')['Sales'].min()

Company
FB      243
GOOG    120
MSFT    124
Name: Sales, dtype: int64

In [9]:
df.groupby('Company')['Sales'].max()

Company
FB      350
GOOG    200
MSFT    340
Name: Sales, dtype: int64

In [10]:
df.groupby('Company')['Sales'].count()

Company
FB      2
GOOG    2
MSFT    2
Name: Sales, dtype: int64

In [11]:
df.groupby('Company')['Sales'].describe()

         count   mean         std    min     25%    50%     75%    max
Company
FB         2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG       2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT       2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
by_comp.describe().transpose()

Company    FB                                                         GOOG  \
        count   mean        std    min     25%    50%     75%    max count
Sales     2.0  296.5  75.660426  243.0  269.75  296.5  323.25  350.0   2.0

Company         ...                  MSFT                                   \
          mean  ...      75%    max count   mean         std    min    25%
Sales    160.0  ...    180.0  200.0   2.0  232.0  152.735065  124.0  178.0

Company
           50%    75%    max
Sales    232.0  286.0  340.0

[1 rows x 24 columns]

In [ ]:
by_comp.describe().transpose()['GOOG']

       count   mean        std    min    25%    50%    75%    max
Sales    2.0  160.0  56.568542  120.0  140.0  160.0  180.0  200.0

# Great Job!