## PANDAS -- PANel Data AnalysiS

**Key Features**

NumPy arrays have a fixed size decided at the time of creation. Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.

**2. Pandas (PANel Data AnalysiS)**
Pandas is a fast and efficient DataFrame object for data manipulation.
It can read and write data in a variety of formats like csv and Text files, Excel, json and SQL database.

It provides high performance DataFrame operations for :
* Numerical and Time series data.

* It is highly optimized for performance and most of its critical code in written in C.

* Pandas are built on top of numpy.

In [ ]:
#Import the Pandas package
import pandas as pd
import numpy as np

## Series
These are 1d labelled ndarray. capable of storing any data type(int, float, string)
* The axis labels are called index. --> They need not be unique but must be hashable type. (immutable).
* An object is hashable if it has a hash valye which never changes during its lifetime.
* All of Python's immutable built in objects are hashable, while mutable containers(lists, dictionary,e.t.c shall not be used as index)

In [ ]:
countries=['India', 'France', 'England','India']
#countries=[[1],[2],[3]]
capitals = ['New Delhi','Paris',' London','New Delhi']
arr = np.array(capitals)
arr

array(['New Delhi', 'Paris', ' London', 'New Delhi'], dtype='<U9')

In [ ]:
#Convert the numpy 1d array to Pandas Sereis.
pd.Series(arr, name='Capital')

0    New Delhi
1        Paris
2       London
3    New Delhi
Name: Capital, dtype: object

In [ ]:
pd.Series(arr, index=countries, name='Capital')

India      New Delhi
France         Paris
England       London
India      New Delhi
Name: Capital, dtype: object

In [ ]:
list1= [0,1,2,0]

In [ ]:
 cap_series = pd.Series(arr, index=list1, name='Capital')
 cap_series

0    New Delhi
1        Paris
2       London
0    New Delhi
Name: Capital, dtype: object

In [ ]:
#Creating pandas Series from a Dictionary
dicts = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80, 'a':90} # Dictionary dont support duplicate keys.
pd.Series(dicts, name='value') # When converting a dictionary to a Series, the dict.key is set as index and dict.value is set as value of the Series.

a    90
b    20
c    30
d    40
e    50
f    60
g    70
h    80
Name: value, dtype: int64

In [ ]:
#########Series Indexing#########
mySeries = pd.Series(dicts, name='value')
mySeries

a    90
b    20
c    30
d    40
e    50
f    60
g    70
h    80
Name: value, dtype: int64

In [ ]:
mySeries['a']

np.int64(90)

In [ ]:
mySeries[0]

/tmp/ipython-input-2378560465.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mySeries[0]

np.int64(90)

In [ ]:
cap_series[0]

0    New Delhi
0    New Delhi
Name: Capital, dtype: object

In [ ]:
mySeries[::-1]

h    80
g    70
f    60
e    50
d    40
c    30
b    20
a    90
Name: value, dtype: int64

In [ ]:
# Pring in reverse order,, last value till the middle of the series
len_series = len(mySeries) # mySreis.size. --> both returns the same value.
mySeries[-1 : -(int(len_series/2)+1) : -1] # end value =-5

h    80
g    70
f    60
e    50
Name: value, dtype: int64

In [ ]:
mySeries[-1 : (int(len_series/2)-1) : -1] # eng value is +3

h    80
g    70
f    60
e    50
Name: value, dtype: int64

In [ ]:
dictss ={"a":10, "b":20, "c":30, "d":40, "e":50}
myser=pd.Series(dictss, name="value")
print(myser)
print("\n---\n")
myser[3:-1:1]

a    10
b    20
c    30
d    40
e    50
Name: value, dtype: int64

---

d    40
Name: value, dtype: int64

In [ ]:
#Perform Mathematical Operations on series
mySeries +mySeries

a    180
b     40
c     60
d     80
e    100
f    120
g    140
h    160
Name: value, dtype: int64

In [ ]:
pd.concat([mySeries, mySeries], axis=1) # Width will increase -->

   value  value
a     90     90
b     20     20
c     30     30
d     40     40
e     50     50
f     60     60
g     70     70
h     80     80

In [ ]:
pd.concat([mySeries, mySeries], axis=0) # length increases.

a    90
b    20
c    30
d    40
e    50
f    60
g    70
h    80
a    90
b    20
c    30
d    40
e    50
f    60
g    70
h    80
Name: value, dtype: int64

## DataFrames
DataFrames are 2D data structures having data aligned in tabular forma.

* Data is aligned in rows( index), and columns and can store any data types like int, string , float, boolean.

In [ ]:
#Create an empty Data Frame
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
fruits = ['Apple','Banana','Mango','Grapes']
pd.DataFrame(fruits, columns=['Fruits']) # Columns is used to set the column name

   Fruits
0   Apple
1  Banana
2   Mango
3  Grapes

In [ ]:
#Create a DataFrame from Nested Lists
people = [['Rick', 60, 'O+'], ['Monty',10,'O+'], ['summer', 45, 'A+'], ['Beth', 18, 'B+']]
df = pd.DataFrame(people, columns=['Name', 'Age', 'Blood Group'])
df

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  summer   45          A+
3    Beth   18          B+

In [ ]:
#Create DataFrame from Dictionary
people = {'Name':['Rick', 'Monty', 'Summer', 'Beth'], 'Age':[60, 10, 45, 18], 'Blood Group':['O+', 'O+', 'A+', 'B+']}
people_df = pd.DataFrame(people)
people_df

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+

In [ ]:
dictss ={"a":[10], "b":[20], "c":[30], "d":[40], "e":[50]}
myser=pd.DataFrame(dictss)
print(myser) # Same key is treated as index in Series but treated as column in DataFrame

    a   b   c   d   e
0  10  20  30  40  50

Takeways:
 We can create data frame from various inputs like
 * Lists
 * Nested Lists
 * Ductionary
 Also, pandas dataframes are mutable and potentially heterogenous tabluar structure.

In [ ]:
#Loading files into DataFrame:
#DataFrame can load data from amny types of files like csv, json, excel sheet, text, json, sql DB...yaml..#
#pd.read_csv('filename')

### Attributes of a DataFrame

In [ ]:
print(people_df)

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+

In [ ]:
print(people_df.dtypes) # for numerical data --> int, float, // for boolean --. bool // for string--> obj.

Name           object
Age             int64
Blood Group    object
dtype: object

In [ ]:
# Check the column names, number of records , datatypes of the records.
print(people_df.info()) # .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         4 non-null      object
 1   Age          4 non-null      int64
 2   Blood Group  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None

In [ ]:
# Check the number of records of each column
people_df.count()

Name           4
Age            4
Blood Group    4
dtype: int64

In [ ]:
# Check the index of the DataFrame
people_df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# Set any of the column as an index
print(people_df)

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+

In [ ]:
people_df = people_df.set_index('Name')

In [ ]:
people_df

        Age Blood Group
Name
Rick     60          O+
Monty    10          O+
Summer   45          A+
Beth     18          B+

In [ ]:
people = {'Name':['Rick', 'Monty', 'Summer', 'Beth','Rick'], 'Age':[60, 10, 45, 18,10], 'Blood Group':['O+', 'O+', 'A+', 'B+', 'B-']}
people_df = pd.DataFrame(people)
people_df

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+
4    Rick   10          B-

In [ ]:
people_df.set_index('Name', inplace=True)

In [ ]:
people_df

        Age Blood Group
Name
Rick     60          O+
Monty    10          O+
Summer   45          A+
Beth     18          B+
Rick     10          B-

In [ ]:
# Reset the index of people_df
people_df.reset_index(inplace=True)

In [ ]:
people_df

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+
4    Rick   10          B-

Selection, Addition, Deletion

In [ ]:
# Select a specific or more columns from the DF.
people_df

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+
4    Rick   10          B-

In [ ]:
# Select only name column
people_df['Blood Group']

0    O+
1    O+
2    A+
3    B+
4    B-
Name: Blood Group, dtype: object

In [ ]:
#people_df.Blood Group --> will throw error

In [ ]:
# Select multiple columns
people_df[['Name', 'Age']]

     Name  Age
0    Rick   60
1   Monty   10
2  Summer   45
3    Beth   18
4    Rick   10

In [ ]:
people_df['Salary'] = [10,20,30,40,50] # Creating a new Column

In [ ]:
people_df

     Name  Age Blood Group  Salary
0    Rick   60          O+      10
1   Monty   10          O+      20
2  Summer   45          A+      30
3    Beth   18          B+      40
4    Rick   10          B-      50

In [ ]:
# Delete a column
del people_df['Salary']

In [ ]:
people_df

     Name  Age Blood Group
0    Rick   60          O+
1   Monty   10          O+
2  Summer   45          A+
3    Beth   18          B+
4    Rick   10          B-

In [ ]:
#

In [ ]:
people_df['Age']= [10,20,30,40,50]
people_df

     Name  Age Blood Group
0    Rick   10          O+
1   Monty   20          O+
2  Summer   30          A+
3    Beth   40          B+
4    Rick   50          B-

In [ ]:
people_df['Null Col'] = 'India' # Broadcasting.

In [ ]:
var = None

In [ ]:
type(var)

NoneType

In [ ]:
people_df

     Name  Age Blood Group Null Col
0    Rick   10          O+    India
1   Monty   20          O+    India
2  Summer   30          A+    India
3    Beth   40          B+    India
4    Rick   50          B-    India

In [ ]:
#Operations on DataFrame Columns
print(people_df)
people_df['Score']=[10,20,30,40,50]
people_df

     Name  Age Blood Group Null Col
0    Rick   10          O+    India
1   Monty   20          O+    India
2  Summer   30          A+    India
3    Beth   40          B+    India
4    Rick   50          B-    India

     Name  Age Blood Group Null Col  Score
0    Rick   10          O+    India     10
1   Monty   20          O+    India     20
2  Summer   30          A+    India     30
3    Beth   40          B+    India     40
4    Rick   50          B-    India     50

In [ ]:
#Addition of two columns and storing it in a new col in the same DF # Similarly we can do any other mathematical operation also.
people_df['Total'] = people_df['Age'] + people_df['Score']
people_df

     Name  Age Blood Group Null Col  Score  Total
0    Rick   10          O+    India     10     20
1   Monty   20          O+    India     20     40
2  Summer   30          A+    India     30     60
3    Beth   40          B+    India     40     80
4    Rick   50          B-    India     50    100

In [ ]:
# We can also remove columns using drop
people_df.drop('Total', axis=1, inplace=True)

In [ ]:
people_df

     Name  Age Blood Group Null Col  Score
0    Rick   10          O+    India     10
1   Monty   20          O+    India     20
2  Summer   30          A+    India     30
3    Beth   40          B+    India     40
4    Rick   50          B-    India     50

In [ ]:
# Drop a row in a dataframe.
people_df.drop(4, axis=0, inplace=True)

In [ ]:
people_df

     Name  Age Blood Group Null Col  Score
0    Rick   10          O+    India     10
1   Monty   20          O+    India     20
2  Summer   30          A+    India     30
3    Beth   40          B+    India     40

In [ ]:
people_df.set_index('Name', inplace=True)

In [ ]:
people_df

        Age Blood Group Null Col  Score
Name
Rick     10          O+    India     10
Monty    20          O+    India     20
Summer   30          A+    India     30
Beth     40          B+    India     40

In [ ]:
# Drop a row having a particular value.
# Drop the row where the name is Summer
#people_df.drop(people_df[people_df['Name']=='Summer'].index, inplace=True)
people_df.drop('Summer', axis=0, inplace=True)
people_df

       Age Blood Group Null Col  Score
Name
Rick    10          O+    India     10
Monty   20          O+    India     20
Beth    40          B+    India     40

In [ ]:
# Drop the row where Blood Group is B+ve.
#Solution : Find the index where the blood group is B+ve.
Bpos_index = people_df[people_df['Blood Group']=='B+'].index
people_df.drop(Bpos_index, axis=0, inplace=True)

In [ ]:
people_df

       Age Blood Group Null Col  Score
Name
Rick    10          O+    India     10
Monty   20          O+    India     20

Date:13/09/2025
## Indexing in DataFrame
There are two type of indexing in pandas
* Using numbers(row or column index) iloc
* Using names(record_row or column name) loc

In [ ]:
import pandas as pd
import numpy as np
market_df = pd.read_csv('https://raw.githubusercontent.com/amity1415/eKeeda/refs/heads/main/Rawdata/SuperMarket.csv')
market_df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
market_df.loc[1:5]

,ID,Address,City,State,Country,Name,Employees
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
# Set ID as index
market_df.set_index('ID', inplace=True)
market_df

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
market_df.index

Index([1, 2, 3, 4, 5, 6], dtype='int64', name='ID')

In [ ]:
###Indexing using iloc
#Print me first 3 rows and 3 cols  of the DF
market_df.iloc[:3, :3]

           Address           City             State
ID
1     3666 21st St  San Francisco          CA 94114
2   735 Dolores St  San Francisco          CA 94119
3      332 Hill St  San Francisco  California 94114

In [ ]:
# Selected rows and selected columns in the dataframe. # df.iloc[ row_op , col_op]
market_df.iloc[ :3 , -1:-4:-1 ]

    Employees         Name Country
ID
1           8      Madeira     USA
2          15  Bready Shop     USA
3          25  Super River     USA

In [ ]:
# Selected rows and selected columns in the dataframe. # df.iloc[ row_op , col_op]
market_df.iloc[[ 3,4,5 ] , [1,3,5]  ] # If you want specific rows and specific colms, prvide them as part of a list.

             City Country  Employees
ID
4   San Francisco     USA         10
5   San Francisco     USA         12
6   San Francisco     USA         20

In [ ]:
market_df.loc[1:6 , "Address":"Employees"] # Give proper index value and col value.

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
market_df.loc[ 6:1:-1, 'Employees' : 'Address':-1]

,Employees,Name,Country,State,City,Address
ID,,,,,,
6,20,Richvalley,USA,CA 94114,San Francisco,551 Alvarado St
5,12,Sanchez,USA,California,San Francisco,1056 Sanchez St
4,10,Ben's Shop,USA,CA 94114,San Francisco,3995 23rd St
3,25,Super River,USA,California 94114,San Francisco,332 Hill St
2,15,Bready Shop,USA,CA 94119,San Francisco,735 Dolores St
1,8,Madeira,USA,CA 94114,San Francisco,3666 21st St

In [ ]:
# If we do not use iloc/ loc, then can we do slicing
#Ans: Is yes, but only at row level.

## Merging & Concating

In [ ]:
#Concat
df3=pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                  'C':['C0','C1','C2','C3'],
                  'D':['D0','D1','D2','D3']},
                 index=[0,1,2,3])
df4=pd.DataFrame({'E':['E2','E3','E4','E5'],
                  'F':['F2','F3','F4','F5'],
                  'C':['C2','C3','C4','C5'],
                  'D':['D2','D3','D4','D5']},
                 index=[2,3,4,5])

In [ ]:
print(df3)
print('--------')
print(df4)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
--------
    E   F   C   D
2  E2  F2  C2  D2
3  E3  F3  C3  D3
4  E4  F4  C4  D4
5  E5  F5  C5  D5

In [ ]:
pd.concat([df3, df4], axis=1)

     A    B    C    D    E    F    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   E2   F2   C2   D2
3   A3   B3   C3   D3   E3   F3   C3   D3
4  NaN  NaN  NaN  NaN   E4   F4   C4   D4
5  NaN  NaN  NaN  NaN   E5   F5   C5   D5

In [ ]:
pd.concat([df3, df4], axis=0)

     A    B   C   D    E    F
0   A0   B0  C0  D0  NaN  NaN
1   A1   B1  C1  D1  NaN  NaN
2   A2   B2  C2  D2  NaN  NaN
3   A3   B3  C3  D3  NaN  NaN
2  NaN  NaN  C2  D2   E2   F2
3  NaN  NaN  C3  D3   E3   F3
4  NaN  NaN  C4  D4   E4   F4
5  NaN  NaN  C5  D5   E5   F5

In [ ]:
df1 = pd.DataFrame({
    'id': [1,2,3,4,5]
    ,'name': ['A','B','C','D','E']
    ,'sub': ['sub1','sub2','sub3','sub4','sub5']
})

In [ ]:
df2 = pd.DataFrame({
    'id': [3,4,5,6,7]
    ,'name': ['C','D','E','F','H']
    ,'sub': ['sub3','sub4','sub5','sub6','sub7']
})

In [ ]:
#Concatenate 2 DataFrames
#We can perform concetanation along rows or along columns
pd.concat([df1, df2], axis=0) # Along rows

   id name   sum
0   1    A  sub1
1   2    B  sub2
2   3    C  sub3
3   4    D  sub4
4   5    E  sub5
0   3    C  sub3
1   4    D  sub4
2   5    E  sub5
3   6    F  sub6
4   7    H  sub7

In [ ]:
pd.concat([df1, df2], axis=1)

   id name   sub  id name   sub
0   1    A  sub1   3    C  sub3
1   2    B  sub2   4    D  sub4
2   3    C  sub3   5    E  sub5
3   4    D  sub4   6    F  sub6
4   5    E  sub5   7    H  sub7

In [ ]:
# Appending in DataFrame.
df3 = pd.DataFrame({'id':[10],
                    'name': ['z'],
                    'sub' : ['sub10']})
df3

   id name    sub
0  10    z  sub10

In [ ]:
# Appending in DataFrame.
df3 = pd.DataFrame({'id':[10],
                    'name': ['z'],
                    'sub' : ['sub10']})
# Use pd.concat() instead of append() because it has been removed from the recent versions

In [ ]:
#Merging in DataFrame:
#This is used to join two dataframes based on any column as key.
print(df1)
print('-----')
print(df2)

   id name   sub
0   1    A  sub1
1   2    B  sub2
2   3    C  sub3
3   4    D  sub4
4   5    E  sub5
-----
   id name   sub
0   3    C  sub3
1   4    D  sub4
2   5    E  sub5
3   6    F  sub6
4   7    H  sub7

In [ ]:
pd.merge(left=df1, right= df2, how='inner', on='id') # Returns only those values where id is common in both the dataframes.

   id name_x sub_x name_y sub_y
0   3      C  sub3      C  sub3
1   4      D  sub4      D  sub4
2   5      E  sub5      E  sub5

In [ ]:
pd.merge(left=df1, right= df2, how='left', on='id')

   id name_x sub_x name_y sub_y
0   1      A  sub1    NaN   NaN
1   2      B  sub2    NaN   NaN
2   3      C  sub3      C  sub3
3   4      D  sub4      D  sub4
4   5      E  sub5      E  sub5

In [ ]:
pd.merge(left=df1, right= df2, how='right', on='id')

   id name_x sub_x name_y sub_y
0   3      C  sub3      C  sub3
1   4      D  sub4      D  sub4
2   5      E  sub5      E  sub5
3   6    NaN   NaN      F  sub6
4   7    NaN   NaN      H  sub7

In [ ]:
pd.merge(left=df1, right= df2, how='outer', on='id')

   id name_x sub_x name_y sub_y
0   1      A  sub1    NaN   NaN
1   2      B  sub2    NaN   NaN
2   3      C  sub3      C  sub3
3   4      D  sub4      D  sub4
4   5      E  sub5      E  sub5
5   6    NaN   NaN      F  sub6
6   7    NaN   NaN      H  sub7

In [ ]:
pd.merge(left=df1, right= df2, how='outer', on=['id', 'name']) # Here we are joining based on 2 conditions, i.e. we have two keys.

   id name sub_x sub_y
0   1    A  sub1   NaN
1   2    B  sub2   NaN
2   3    C  sub3  sub3
3   4    D  sub4  sub4
4   5    E  sub5  sub5
5   6    F   NaN  sub6
6   7    H   NaN  sub7

In [ ]:
#Conditionals in DataFrame:
# Perform comparisions on the records of DatFrame
# Output of comparision is of boolean datatype
#You can use this boolean to filter out records from the DataFrame.
market_df

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
market_df['Employees']>=15

ID
1    False
2     True
3     True
4    False
5    False
6     True
Name: Employees, dtype: bool

In [ ]:
# Print the filtered dataframe where the No of Employees is greater than or equal to 15
market_df[market_df['Employees']>=15]

,Address,City,State,Country,Name,Employees
ID,,,,,,
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
df_emp_gt15 = market_df[market_df['Employees']>=15]
df_emp_gt15

,Address,City,State,Country,Name,Employees
ID,,,,,,
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
# print Address, City, State in the above filtered DataFrame
df_emp_gt15[['Address','City','State']]

            Address           City             State
ID
2    735 Dolores St  San Francisco          CA 94119
3       332 Hill St  San Francisco  California 94114
6   551 Alvarado St  San Francisco          CA 94114

In [ ]:
df_copy = df_emp_gt15.copy()

In [ ]:
#df_copy = df_emp_gt15. # This copies the index and not values Hence any change in df_copy will impact df_emp_gt15.

In [ ]:
df_copy.drop('Country', axis=1, inplace=True)
df_copy

            Address           City             State         Name  Employees
ID
2    735 Dolores St  San Francisco          CA 94119  Bready Shop         15
3       332 Hill St  San Francisco  California 94114  Super River         25
6   551 Alvarado St  San Francisco          CA 94114   Richvalley         20

In [ ]:
df_emp_gt15

,Address,City,State,Country,Name,Employees
ID,,,,,,
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
df_emp_gt15.columns
df_emp_gt15.columns != 'Country'

array([ True,  True,  True, False,  True,  True])

In [ ]:
# TO exclude 1 or more than 1 column from a DataFrame
col_to_exclude = ['Country']
df_excluded_loc = df_emp_gt15.loc[:, df_emp_gt15.columns != 'Country']
df_excluded_loc

            Address           City             State         Name  Employees
ID
2    735 Dolores St  San Francisco          CA 94119  Bready Shop         15
3       332 Hill St  San Francisco  California 94114  Super River         25
6   551 Alvarado St  San Francisco          CA 94114   Richvalley         20

In [ ]:
#Using the ~ operator
df_excluded_loc = df_emp_gt15.loc[:, ~(df_emp_gt15.columns == 'Country')]
df_excluded_loc

            Address           City             State         Name  Employees
ID
2    735 Dolores St  San Francisco          CA 94119  Bready Shop         15
3       332 Hill St  San Francisco  California 94114  Super River         25
6   551 Alvarado St  San Francisco          CA 94114   Richvalley         20

In [ ]:
df_excluded_loc = df_emp_gt15.loc[:, ~(df_emp_gt15.columns.isin(['Country', 'Name']))]
df_excluded_loc

            Address           City             State  Employees
ID
2    735 Dolores St  San Francisco          CA 94119         15
3       332 Hill St  San Francisco  California 94114         25
6   551 Alvarado St  San Francisco          CA 94114         20

In [ ]:
market_df

,Address,City,State,Country,Name,Employees
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
#Print those values in the DF where no of employees >15 and are from state 'CA 94114'
market_df[(market_df['State']=='CA 94114') & (market_df['Employees']>=15)]

            Address           City     State Country        Name  Employees
ID
6   551 Alvarado St  San Francisco  CA 94114     USA  Richvalley         20

In [ ]:
#Multi Index DataFrame
import pandas as pd

company_df = {
    'Company' : ['Apple', 'Apple', 'Apple', 'Google', 'Google', 'Google'],
    'Year' : [2012, 2013, 2014, 2015, 2011, 2012],
    'Revenue' : [1000, 2000, 3000, 4000, 5000, 6000],
    'Profit' : [100, 200, 300, 400, 500, 600],
    'Employee': [1000, 2000, 3000, 4000, 5000, 6000]
}
company_df

{'Company': ['Apple', 'Apple', 'Apple', 'Google', 'Google', 'Google'],
 'Year': [2012, 2013, 2014, 2015, 2011, 2012],
 'Revenue': [1000, 2000, 3000, 4000, 5000, 6000],
 'Profit': [100, 200, 300, 400, 500, 600],
 'Employee': [1000, 2000, 3000, 4000, 5000, 6000]}

In [ ]:
cmp_df = pd.DataFrame(company_df)
cmp_df

  Company  Year  Revenue  Profit  Employee
0   Apple  2012     1000     100      1000
1   Apple  2013     2000     200      2000
2   Apple  2014     3000     300      3000
3  Google  2015     4000     400      4000
4  Google  2011     5000     500      5000
5  Google  2012     6000     600      6000

In [ ]:
cmp_df.set_index(['Company'], inplace=True)
cmp_df

         Year  Revenue  Profit  Employee
Company
Apple    2012     1000     100      1000
Apple    2013     2000     200      2000
Apple    2014     3000     300      3000
Google   2015     4000     400      4000
Google   2011     5000     500      5000
Google   2012     6000     600      6000

In [ ]:
cmp_df.reset_index(inplace=True)

In [ ]:
cmp_df

  Company  Year  Revenue  Profit  Employee
0   Apple  2012     1000     100      1000
1   Apple  2013     2000     200      2000
2   Apple  2014     3000     300      3000
3  Google  2015     4000     400      4000
4  Google  2011     5000     500      5000
5  Google  2012     6000     600      6000

In [ ]:
cmp_df.set_index('Year', inplace=True) # When ever we are setting index on top of existing one, ensure to reset index first.
cmp_df

     Company  Revenue  Profit  Employee
Year
2012   Apple     1000     100      1000
2013   Apple     2000     200      2000
2014   Apple     3000     300      3000
2015  Google     4000     400      4000
2011  Google     5000     500      5000
2012  Google     6000     600      6000

In [ ]:
cmp_df.reset_index(inplace=True)

In [ ]:
cmp_df.set_index(['Company', 'Year'], inplace=True)
cmp_df

              Revenue  Profit  Employee
Company Year
Apple   2012     1000     100      1000
        2013     2000     200      2000
        2014     3000     300      3000
Google  2015     4000     400      4000
        2011     5000     500      5000
        2012     6000     600      6000

In [ ]:
cmp_df.loc[('Apple',2014)]

Revenue     3000
Profit       300
Employee    3000
Name: (Apple, 2014), dtype: int64

In [ ]:
# Access Data with MultiIndexing

In [ ]:
cmp_df.loc['Apple'].loc[[2013, 2014]] # location chaining.

      Revenue  Profit  Employee
Year
2013     2000     200      2000
2014     3000     300      3000

In [ ]:
# I want to access a particular index, through Year.
cmp_df.xs('Apple', level='Company')

      Revenue  Profit  Employee
Year
2012     1000     100      1000
2013     2000     200      2000
2014     3000     300      3000

In [ ]:
cmp_df.xs(2012, level='Year')

         Revenue  Profit  Employee
Company
Apple       1000     100      1000
Google      6000     600      6000

In [ ]:
# I want to access a particular index, through Year.
# cmp_df.xs((2013,2014), level='Year') # This will cause a KeyError as xs expects a single key for the level
# To access multiple years, filter the DataFrame based on the 'Year' index level
cmp_df.loc[cmp_df.index.get_level_values('Year').isin([2013, 2014,2015])]

              Revenue  Profit  Employee
Company Year
Apple   2013     2000     200      2000
        2014     3000     300      3000
Google  2015     4000     400      4000

In [ ]:
#GroupBy -- For Data Analysis this is the most used tool in Pandas.

## Group By

In [ ]:
import seaborn as sns
import pandas as pd
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips.groupby(['sex', 'time'])['tip'].mean()

/tmp/ipython-input-351847192.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['sex', 'time'])['tip'].mean()

sex     time
Male    Lunch     2.882121
        Dinner    3.144839
Female  Lunch     2.582857
        Dinner    3.002115
Name: tip, dtype: float64

In [ ]:
tips.groupby(['sex', 'time','day'])[['tip','total_bill']].agg(['mean', 'sum','count'])

/tmp/ipython-input-3903401504.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['sex', 'time','day'])[['tip','total_bill']].agg(['mean', 'sum','count'])

                         tip               total_bill
                        mean     sum count       mean      sum count
sex    time   day
Male   Lunch  Thur  2.980333   89.41    30  18.714667   561.44    30
              Fri   1.900000    5.70     3  11.386667    34.16     3
              Sat        NaN    0.00     0        NaN     0.00     0
              Sun        NaN    0.00     0        NaN     0.00     0
       Dinner Thur       NaN    0.00     0        NaN     0.00     0
              Fri   3.032857   21.23     7  23.487143   164.41     7
              Sat   3.083898  181.95    59  20.802542  1227.35    59
              Sun   3.220345  186.78    58  21.887241  1269.46    58
Female Lunch  Thur  2.561935   79.42    31  16.648710   516.11    31
              Fri   2.745000   10.98     4  13.940000    55.76     4
              Sat        NaN    0.00     0        NaN     0.00     0
              Sun        NaN    0.00     0        NaN     0.00     0
       Dinner Thur  3.000000    3.00     1  18.780000    18.78     1
              Fri   2.810000   14.05     5  14.310000    71.55     5
              Sat   2.801786   78.45    28  19.680357   551.05    28
              Sun   3.367222   60.61    18  19.872222   357.70    18

In [ ]:
tips.groupby(['sex', 'time','day'])\
 [['tip','total_bill']] \
.agg(['mean', 'sum','count']) \
.sort_values(by=[('tip', 'count'), ('total_bill','sum')], ascending=[False,True])

/tmp/ipython-input-1465376379.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['sex', 'time','day'])[['tip','total_bill']] \

                         tip               total_bill
                        mean     sum count       mean      sum count
sex    time   day
Male   Dinner Sat   3.083898  181.95    59  20.802542  1227.35    59
              Sun   3.220345  186.78    58  21.887241  1269.46    58
Female Lunch  Thur  2.561935   79.42    31  16.648710   516.11    31
Male   Lunch  Thur  2.980333   89.41    30  18.714667   561.44    30
Female Dinner Sat   2.801786   78.45    28  19.680357   551.05    28
              Sun   3.367222   60.61    18  19.872222   357.70    18
Male   Dinner Fri   3.032857   21.23     7  23.487143   164.41     7
Female Dinner Fri   2.810000   14.05     5  14.310000    71.55     5
       Lunch  Fri   2.745000   10.98     4  13.940000    55.76     4
Male   Lunch  Fri   1.900000    5.70     3  11.386667    34.16     3
Female Dinner Thur  3.000000    3.00     1  18.780000    18.78     1
Male   Lunch  Sat        NaN    0.00     0        NaN     0.00     0
              Sun        NaN    0.00     0        NaN     0.00     0
       Dinner Thur       NaN    0.00     0        NaN     0.00     0
Female Lunch  Sat        NaN    0.00     0        NaN     0.00     0
              Sun        NaN    0.00     0        NaN     0.00     0

In [ ]:
tips.groupby(['sex','day'])[['tip','total_bill', 'time']].agg(['count'])\
.sort_values(by=[('tip','count'), ('time', 'count')], ascending=[False, True])

/tmp/ipython-input-2482259782.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby(['sex','day'])[['tip','total_bill', 'time']].agg(['count'])\

              tip total_bill  time
            count      count count
sex    day
Male   Sat     59         59    59
       Sun     58         58    58
Female Thur    32         32    32
Male   Thur    30         30    30
Female Sat     28         28    28
       Sun     18         18    18
Male   Fri     10         10    10
Female Fri      9          9     9

14/09/2025

### Operations on a DataFrame

In [ ]:
tips.head() #Observe the first 5 elements of the DF

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips['size'].unique() # Unique Values

array([2, 3, 4, 1, 6, 5])

In [ ]:
tips['size'].nunique() #Count of Unique Values

6

In [ ]:
tips.count() # No of rows at each column level

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

In [ ]:
tips['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

Apply Functions on a DataFrame

In [ ]:
tips['tip']*2 # Scalar multiplication to all the values in the tip column

0       2.02
1       3.32
2       7.00
3       6.62
4       7.22
       ...
239    11.84
240     4.00
241     4.00
242     3.50
243     6.00
Name: tip, Length: 244, dtype: float64

In [ ]:
def times2(x):
  num =x
  if x %1==0:
    num *=2
  return num

In [ ]:
#In order to use any function with a particular column of a DataFrame we use .apply keyword
tips['tip'].apply(times2)

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    4.00
241    4.00
242    1.75
243    6.00
Name: tip, Length: 244, dtype: float64

In [ ]:
tips['size'].apply(lambda x: x * 2 if x % 2 == 0 else x)

0      4
1      3
2      3
3      4
4      8
      ..
239    3
240    4
241    4
242    4
243    4
Name: size, Length: 244, dtype: int64

In [ ]:
# Assignment : Implement map, filter and reduce function in Pandas DataFrame at column level.

## Time Series in Pandas

In [ ]:
#Here we will explore the DateTime functions provided by Pandas and how efficient it is to analyse TIme Series Data.
import pandas as pd
air_df = pd.read_csv('https://raw.githubusercontent.com/amity1415/eKeeda/refs/heads/main/Rawdata/AQI.csv')
air_df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
# Date and Time columns are object datatype. We will need to convert them to datetime format.
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   int64
 7   NOx(GT)        9357 non-null   int64
 8   PT08.S3(NOx)   9357 non-null   int64
 9   NO2(GT)        9357 non-null   int64
 10  PT08.S4(NO2)   9357 non-null   int64
 11  PT08.S5(O3)    9357 non-null   int64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(5), int64(8), object(2)
memory usage: 1.1+ MB

In [ ]:
air_df['Date'] = pd.to_datetime(air_df['Date'], format='%m/%d/%Y')
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   datetime64[ns]
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   int64
 7   NOx(GT)        9357 non-null   int64
 8   PT08.S3(NOx)   9357 non-null   int64
 9   NO2(GT)        9357 non-null   int64
 10  PT08.S4(NO2)   9357 non-null   int64
 11  PT08.S5(O3)    9357 non-null   int64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(8), object(1)
memory usage: 1.1+ MB

In [ ]:
air_df['Time'].unique()

array(['18:00:00', '19:00:00', '20:00:00', '21:00:00', '22:00:00',
       '23:00:00', '0:00:00', '1:00:00', '2:00:00', '3:00:00', '4:00:00',
       '5:00:00', '6:00:00', '7:00:00', '8:00:00', '9:00:00', '10:00:00',
       '11:00:00', '12:00:00', '13:00:00', '14:00:00', '15:00:00',
       '16:00:00', '17:00:00'], dtype=object)

In [ ]:
air_df['Time'] = pd.to_datetime(air_df['Time'], format='%H:%M:%S')
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   datetime64[ns]
 1   Time           9357 non-null   datetime64[ns]
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   int64
 7   NOx(GT)        9357 non-null   int64
 8   PT08.S3(NOx)   9357 non-null   int64
 9   NO2(GT)        9357 non-null   int64
 10  PT08.S4(NO2)   9357 non-null   int64
 11  PT08.S5(O3)    9357 non-null   int64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(8)
memory usage: 1.1 MB

In [ ]:
air_df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,1900-01-01 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004-03-10,1900-01-01 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004-03-10,1900-01-01 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004-03-10,1900-01-01 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004-03-10,1900-01-01 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
# Extrace year from the Date Column
year = air_df['Date'].dt.year
year
air_df['Year']= year

In [ ]:
air_df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Year
0,2004-03-10,1900-01-01 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578,2004
1,2004-03-10,1900-01-01 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255,2004
2,2004-03-10,1900-01-01 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502,2004
3,2004-03-10,1900-01-01 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867,2004
4,2004-03-10,1900-01-01 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888,2004

In [ ]:
#Move the Year column from last to 1st.
last_col = air_df.pop('Year')
air_df.insert(0, 'year', last_col)
air_df.head()

,year,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,2004-03-10,1900-01-01 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,2004-03-10,1900-01-01 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,2004-03-10,1900-01-01 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,2004-03-10,1900-01-01 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,2004-03-10,1900-01-01 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
#Extract Month from the Date Column
month = air_df['Date'].dt.month
month
air_df.insert(1, 'month', month)
air_df.head()

,year,month,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,3,2004-03-10,1900-01-01 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,3,2004-03-10,1900-01-01 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,3,2004-03-10,1900-01-01 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,3,2004-03-10,1900-01-01 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,3,2004-03-10,1900-01-01 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
month = air_df['Date'].dt.month_name()
month
air_df.insert(2, 'month_name', month)
air_df.head()

,year,month,month_name,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,3,March,2004-03-10,1900-01-01 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,3,March,2004-03-10,1900-01-01 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,3,March,2004-03-10,1900-01-01 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,3,March,2004-03-10,1900-01-01 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,3,March,2004-03-10,1900-01-01 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
day = air_df.Date.dt.day
day
air_df.insert(3, 'day', day)
air_df.head()

,year,month,month_name,day,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,3,March,10,2004-03-10,1900-01-01 18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,3,March,10,2004-03-10,1900-01-01 19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,3,March,10,2004-03-10,1900-01-01 20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,3,March,10,2004-03-10,1900-01-01 21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,3,March,10,2004-03-10,1900-01-01 22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
# Extract the Week number from Date Column
week = air_df.Date.dt.weekday_name
week
air_df.insert(5, 'weekday_name', week)
air_df.head()

,year,month,month_name,day,week,weekday_name,weekday,Date,Time,CO(GT),...,C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,3,March,10,2,Wednesday,2,2004-03-10,1900-01-01 18:00:00,2.6,...,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,3,March,10,2,Wednesday,2,2004-03-10,1900-01-01 19:00:00,2.0,...,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,3,March,10,2,Wednesday,2,2004-03-10,1900-01-01 20:00:00,2.2,...,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,3,March,10,2,Wednesday,2,2004-03-10,1900-01-01 21:00:00,2.2,...,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,3,March,10,2,Wednesday,2,2004-03-10,1900-01-01 22:00:00,1.6,...,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
#Print the Week Number from the date
week_num = air_df.Date.dt.isocalendar().week
week_num
air_df.insert(4, 'week_num', week_num)
air_df.head()

,year,month,month_name,day,week_num,week,weekday_name,weekday,Date,Time,...,C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,3,March,10,11,2,Wednesday,2,2004-03-10,1900-01-01 18:00:00,...,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,3,March,10,11,2,Wednesday,2,2004-03-10,1900-01-01 19:00:00,...,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,3,March,10,11,2,Wednesday,2,2004-03-10,1900-01-01 20:00:00,...,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,3,March,10,11,2,Wednesday,2,2004-03-10,1900-01-01 21:00:00,...,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,3,March,10,11,2,Wednesday,2,2004-03-10,1900-01-01 22:00:00,...,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
#https://overapi.com/python --> Use this link for more Python Operations

In [ ]:
day_of_year = air_df.Date.dt.day_of_year
air_df.insert(4, 'day_of_year', day_of_year)
air_df.head()

,year,month,month_name,day,day_of_year,week_num,week,weekday_name,weekday,Date,...,C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004,3,March,10,70,11,2,Wednesday,2,2004-03-10,...,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,2004,3,March,10,70,11,2,Wednesday,2,2004-03-10,...,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2004,3,March,10,70,11,2,Wednesday,2,2004-03-10,...,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,2004,3,March,10,70,11,2,Wednesday,2,2004-03-10,...,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,2004,3,March,10,70,11,2,Wednesday,2,2004-03-10,...,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [ ]:
hour = air_df.Time.dt.hour # Similarly it extracts , dt.minute , dt.second
print(hour.head())

0    18
1    19
2    20
3    21
4    22
Name: Time, dtype: int32

Performing Conditional Operations on Time.
Lets measure the number of records before 9 am.

In [ ]:
timestamp = pd.to_datetime("09:00:00", format='%H:%M:%S')
timestamp

Timestamp('1900-01-01 09:00:00')

In [ ]:
air_df[air_df['Time'] < timestamp]['RH'].mean()

np.float64(49.16119658119658)

In [ ]:
air_df[air_df['Time'] > timestamp]['RH'].mean()

np.float64(32.859373282023085)

In [ ]:
#TimeDelta
from datetime import timedelta
print(air_df['Date'])
print('----------')
print(air_df['Date'] + timedelta(days=1)) # days= -1, hours, minutes, second, month, week, year.

0      2004-03-10
1      2004-03-10
2      2004-03-10
3      2004-03-10
4      2004-03-10
          ...
9352   2005-04-04
9353   2005-04-04
9354   2005-04-04
9355   2005-04-04
9356   2005-04-04
Name: Date, Length: 9357, dtype: datetime64[ns]
----------
0      2004-03-11
1      2004-03-11
2      2004-03-11
3      2004-03-11
4      2004-03-11
          ...
9352   2005-04-05
9353   2005-04-05
9354   2005-04-05
9355   2005-04-05
9356   2005-04-05
Name: Date, Length: 9357, dtype: datetime64[ns]

In [ ]:
#Lets measure the number of records before 01/01/2005
date_stamp = pd.to_datetime("01/01/2005", format='%d/%m/%Y')
date_stamp

Timestamp('2005-01-01 00:00:00')

In [ ]:
air_df[air_df['Date'] < date_stamp].tail()

,year,month,month_name,day,day_of_year,week_num,week,weekday_name,weekday,Date,...,C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
7105,2004,12,December,31,366,53,4,Friday,4,2004-12-31,...,5.3,781,-200,933,-200,906,866,9.3,33.6,0.3958
7106,2004,12,December,31,366,53,4,Friday,4,2004-12-31,...,5.3,780,-200,919,-200,909,884,9.6,32.3,0.3871
7107,2004,12,December,31,366,53,4,Friday,4,2004-12-31,...,5.5,790,-200,915,-200,895,951,9.1,32.5,0.3766
7108,2004,12,December,31,366,53,4,Friday,4,2004-12-31,...,5.6,791,-200,845,-200,936,1195,9.1,37.2,0.4310
7109,2004,12,December,31,366,53,4,Friday,4,2004-12-31,...,4.6,744,-200,882,-200,899,1138,7.8,38.4,0.4085

**Takeaways**

We have seen that by using datetime format we can extract information like year, month, hour, minute etc from time.
We can even retrieve name of the day and day of the year type information.

All these things help to better understand our data which in turn help in drawing important conclusions and insights.

**Conclusion**

Python is a great language for doing data analysis, primarily because of the fantastic ecosystem of data-centric Python packages.
Pandas is one of those packages, and makes importing and analyzing data much easier.

It is an open-source, BSD-licensed Python library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.
Python with Pandas is used in a wide range of fields including academic and commercial domains like finance, economics, statistics, analytics, etc.

They are built on packages like NumPy and matplotlib to give you a single, convenient, place to do most of your data analysis and visualization work.

**Key Features**
Fast and efficient DataFrame object with default and customized indexing.

Tools for loading data into in-memory data objects from different file formats.

Data alignment and integrated handling of missing data.
Reshaping and pivoting of date sets.

Label-based slicing, indexing and subsetting of large data sets.

Columns from a data structure can be deleted or inserted.

Groupby data for aggregation and transformations.

High performance merging and joining of data.

Time Series functionality.